### ISSUE TITLE
Not working in fullscreen 

### ISSUE THREAD

**Issue by stinyo7** [BradyBrenot/huestacean#124]
Sorry if this has been covered elsewhere, but I can't get Huestacean to work in fullscreen on Netflix, Google Play, or Amazon Prime. Oddly enough it works for YouTube. I've tried both Chrome and Edge. Any advice?

**Comment by BradyBrenot** [comment]
They're probably activating whatever mode it is that blocks recording. If
they use HDCP that does it. I'm unaware of any tricks to get around this
but there probably are some. I want to see how OBS records the screen ...

**Comment by BradyBrenot** [comment]
Might work if you turn off hardware acceleration in Chrome settings, but yeah, otherwise it's Windows' built-in HDCP protection stuff, I can't do anything about this.

It doesn't look like OBS can record in this situation either, regardless of the method used to hook the window. At best the browser window and the video controls all show up, but the video itself is still black. At least this is the case for me with Edge; with Chrome, I can still use Huestacean and OBS, but it doesn't go above 1080p on Netflix, I assume it's not using hardware acceleration like Edge / the Windows 10 app do.
