### ISSUE TITLE
crash error 

### ISSUE THREAD

**Issue by Menacer95** [BradyBrenot/huestacean#67]
i get a crash error on mac when i try to open it 

Process:               huestacean [10568]
Path:                  /Users/USER/Desktop/huestacean.app/Contents/MacOS/huestacean
Identifier:            huestacean
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           huestacean [10568]
User ID:               501

Date/Time:             2018-03-29 19:06:40.181 -0700
OS Version:            Mac OS X 10.13.4 (17E182a)
Report Version:        12
Anonymous UUID:        11D47221-C454-F19B-6922-FC9DC1FA6F8D

Time Awake Since Boot: 600000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /Users/USER/Desktop/huestacean.app/Contents/MacOS/huestacean
  Reason: image not found

Binary Images:
       0x1012c0000 -        0x101399ff7 + (??? - ???) <385B401D-AFE2-3803-A8F4-3054F4907ED4> /Users/USER/Desktop/huestacean.app/Contents/MacOS/huestacean
       0x10d515000 -        0x10d55f9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld

Model: MacBookAir6,1, BootROM MBA61.0106.B00, 2 processors, Intel Core i5, 1.3 GHz, 4 GB, SMC 2.12f143
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD TS0128F, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: My Book 1234
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by davemikolaj** [comment]
Process:               huestacean [837]
Path:                  /Applications/huestacean.app/Contents/MacOS/huestacean
Identifier:            huestacean
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           huestacean [837]
User ID:               501

Date/Time:             2018-03-30 19:24:55.725 +1030
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        2BA512FC-8E40-40EB-DAC1-9B319B3E4BC1


Time Awake Since Boot: 530 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /Applications/huestacean.app/Contents/MacOS/huestacean
  Reason: image not found

Binary Images:
       0x109f50000 -        0x10a029ff7 + (??? - ???) <385B401D-AFE2-3803-A8F4-3054F4907ED4> /Applications/huestacean.app/Contents/MacOS/huestacean
       0x10f236000 -        0x10f273dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld

**Comment by kevinvincent** [comment]
Having same issue. Tried installing Qt but get the same error

**Comment by BradyBrenot** [comment]
Uploaded a fixed .app. This is because I didn't rerun macdeployqt and wasn't testing adequately (I renamed my local Qt installation and it reproduced the issue since it couldn't find the framework)
