### ISSUE TITLE
Save more settings

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#7]
Everything on the GUI, including entertainment group selection, monitor, ..., should be saved.

**Comment by Dracrius** [comment]
Will this be in one of the upcoming update? The last update 2.0 alpha 3 while really nice raises the center slowness/dampening way to much for my set up. I have a Lightbar plus right behind my monitor so the old setting of 2 was breath taking while watching movies or trailers and the new default of 10 feels extremely sluggish though I'm guessing this is because of my light placement! I only just realized settings weren't being saved because this was the first time I tried to change something from default. Thanks for your work this program's coming out really nice!

**Comment by banksio** [comment]
@BradyBrenot This sounds good, but would it be possible to add a reset button in case settings are changed inadvertently? Thanks
